server:
  port: 8102
  servlet:
      context-path: /api/theory

spring:
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      bootstrap-servers: localhost:9092
      client-id: theory-service-client
      properties:
        linger.ms : 5_000
      batch-size: 500
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/theory}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}

settings:
  kafka:
    topic: statistic-topic