server:
  port: 8102
  servlet:
      context-path: /api/theory

spring:
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      bootstrap-servers: localhost:9092
      client-id: theory-service-client

settings:
  kafka:
    topic: statistic-topic